version: "3"
virtualmachines:
- name: boundary-worker
  image: instruqt-hashicorp/ubuntu-base
  shell: /bin/bash -l
  environment:
    BOUNDARY_ADDR: http://TODO:9200
    BOUNDARY_WORKER_ADDR: 127.0.0.1:9202
    VAULT_ADDR: http://vault-sql-server:8200
  machine_type: n1-standard-1
- name: vault-sql-server
  image: instruqt-hashicorp/ubuntu-base
  shell: /bin/bash -l
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
  machine_type: n1-standard-1
#https://docs.instruqt.com/how-to-guides/manage-sandboxes/run-a-windows-vm
#Instruqt Defaults
#u: instruqt 
#p: Passw0rd!
- name: windows-server
  image: instruqt/windows-server 
  environment:
    VAULT_ADDR: http://vault-sql-server:8200
  machine_type: n1-standard-1
- name: windows-server-02
  image: instruqt/windows-server 
  environment:
    VAULT_ADDR: http://vault-sql-server:8200
  machine_type: n1-standard-1
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080

# - name: kubernetes
#   image: instruqt/instruqt/k3s-v1-25-0
#   shell: /bin/bash
#   machine_type: n1-standard-1
